[asterisk]
asterisk-nodo1 ansible_host=54.146.194.11
asterisk-nodo2 ansible_host=54.90.127.106

[kamailio]
kamailio-proxy ansible_host=54.158.134.185

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/projects/ansible-homelab/ansible-homelab.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
