[asterisk]
asterisk-nodo1 ansible_host=3.93.167.236
asterisk-nodo2 ansible_host=54.85.4.193

[kamailio]
kamailio-proxy ansible_host=54.211.83.217

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/projects/ansible-homelab/ansible-homelab.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'